#!/bin/bash
javac -cp lib/json-20190722.jar:lib/junit-4.13-rc-1.jar:hamcrest-2.2.jar:bin/com/batchanalyzer src/com/batchanalyzer/*.java -d .
java -cp lib/json-20190722.jar:lib/junit-4.13-rc-1.jar:lib/hamcrest-2.2.jar:. com.batchanalyzer.TestRunner